# Generated by Django 5.0.2 on 2024-03-31 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_performed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='collected',
            field=models.BooleanField(default=False),
        ),
    ]
