# Generated by Django 5.0.2 on 2024-03-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_category_image_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=128)),
                ('qr_code', models.ImageField(blank=True, upload_to='table_qr_codes/')),
            ],
        ),
    ]
