# Generated by Django 5.0.2 on 2024-03-15 21:21

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_remove_table_password_remove_table_qr_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'تصنيف', 'verbose_name_plural': 'تصنيفات'},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, max_length=255, populate_from='name', unique=True, verbose_name='الاسم المختصر'),
            preserve_default=False,
        ),
    ]
